name: "Release Candidate Action"
description: "Creates a Release Candidate branch, creates a Github Issue, and posts to a Slack webhook."
inputs:
  github-token:
    description: "Access token for your repository"
    required: true
runs:
  using: "node16"
  main: "index.js"
